x-common-env: &common-env
  MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
  MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-nba-raw-data}
  MINIO_SECURE: ${MINIO_SECURE:-false}
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  DB_HOST: postgres
  DB_PORT: ${DB_PORT:-5432}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}

services:
  data_ingestion:
    image: ${DOCKER_REGISTRY}/data-ingestion:latest
    environment:
      <<: *common-env
    volumes:
      - ./:/app/data_pipeline_services
      - ../config:/app/config
      - shared_tmp:/tmp
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  data_processing:
    image: ${DOCKER_REGISTRY}/data-processing:latest
    environment:
      <<: *common-env
    volumes:
      - ./:/app/data_pipeline_services
      - ../config:/app/config
      - shared_tmp:/tmp
    depends_on:
      data_ingestion:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  minio_data:
  postgres_data:
  shared_tmp:
