scraping_job:
  season: "2023-24"
  start_date: "12-01" # MM-DD
  end_date: "12-05" # MM-DD

# if start_date and end_date empty
default_nba_dates:
  start: "10-01"
  end: "06-30"

minio:
  endpoint: "127.0.0.1:9001"
  access_key: "${MINIO_ROOT_USER}"
  secret_key: "${MINIO_ROOT_PASSWORD}"
  secure: false
  bucket_name: "nba-raw-data"
  output_dir: "nba_data"
