services:
  airflow-webserver:
    image: apache/airflow:2.10.1
    depends_on:
      - data_pipeline_services_postgres_1
      - data_pipeline_services_minio_1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@data_pipeline_services_postgres_1/${DB_NAME}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../data_pipeline_services:/opt/airflow/data_pipeline_services
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - airflow_network
      - data_pipeline_services_default

  airflow-scheduler:
    image: apache/airflow:2.10.1
    depends_on:
      - airflow-webserver
      - data_pipeline_services_postgres_1
      - data_pipeline_services_minio_1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@data_pipeline_services_postgres_1/${DB_NAME}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../data_pipeline_services:/opt/airflow/data_pipeline_services
    command: scheduler
    networks:
      - airflow_network
      - data_pipeline_services_default

networks:
  airflow_network:
    driver: bridge
  data_pipeline_services_default:
    external: true
